### ISSUE TITLE
Crashes on 1.19.2

### ISSUE THREAD

**Issue by SoGoodArt** [ThatGravyBoat/Persona#5]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2022-12-22 14:19:08
Description: Unexpected error

java.lang.IncompatibleClassChangeError: Class net.minecraft.class_2585 does not implement the requested interface net.minecraft.class_2561
	at net.minecraft.class_6382.method_37034(class_6382.java:8)
	at net.minecraft.class_437.method_37062(class_437.java:573)
	at net.minecraft.class_6385.method_37044(class_6385.java:34)
	at net.minecraft.class_437.method_37065(class_437.java:565)
	at net.minecraft.class_437.method_37064(class_437.java:560)
	at net.minecraft.class_437.method_25423(class_437.java:381)
	at net.minecraft.class_310.method_1507(class_310.java:1035)
	at tech.thatgravyboat.persona.common.entity.PersonaSpawnEgg.openScreen(PersonaSpawnEgg.java:46)
	at tech.thatgravyboat.persona.common.entity.PersonaSpawnEgg.method_7884(PersonaSpawnEgg.java:38)
	at net.minecraft.class_1799.method_7981(class_1799.java:264)
	at net.minecraft.class_636.method_41934(class_636.java:363)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1748)
	at net.minecraft.class_310.redirect$bba000$onDoItemUse(class_310.java:9016)
	at net.minecraft.class_310.method_1508(class_310.java:2002)
	at net.minecraft.class_310.method_1574(class_310.java:1829)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_6382.method_37034(class_6382.java:8)
	at net.minecraft.class_437.method_37062(class_437.java:573)
	at net.minecraft.class_6385.method_37044(class_6385.java:34)
	at net.minecraft.class_437.method_37065(class_437.java:565)
	at net.minecraft.class_437.method_37064(class_437.java:560)
	at net.minecraft.class_437.method_25423(class_437.java:381)
	at net.minecraft.class_310.method_1507(class_310.java:1035)
	at tech.thatgravyboat.persona.common.entity.PersonaSpawnEgg.openScreen(PersonaSpawnEgg.java:46)
	at tech.thatgravyboat.persona.common.entity.PersonaSpawnEgg.method_7884(PersonaSpawnEgg.java:38)
	at net.minecraft.class_1799.method_7981(class_1799.java:264)
	at net.minecraft.class_636.method_41934(class_636.java:363)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1748)
	at net.minecraft.class_310.redirect$bba000$onDoItemUse(class_310.java:9016)
	at net.minecraft.class_310.method_1508(class_310.java:2002)

-- Affected level --
Details:
	All players: 1 total; [class_746['imTonk'/541, l='ClientLevel', x=331.43, y=72.00, z=105.00]]
	Chunk stats: 1024, 224
	Level dimension: minecraft:overworld
	Level spawn location: World: (288,78,80), Section: (at 0,14,0 in 18,4,5; chunk contains blocks 288,-64,80 to 303,319,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 10123 game time, 10123 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ThatGravyBoat** [comment]
This mod only supports 1.18.2
